
__author__ = "Dmitry Philippov"
 
import sys
 
sys.stdout = open('sorting.out', 'w')
 
def main():
    print('''5
S 0 _ _ _ _ -> process 0 ^ 30 ^ _ ^ _ ^ _ ^
S 1 _ _ _ _ -> process 1 ^ 30 ^ _ ^ _ ^ _ ^
process 0 0 _ _ _ -> AC 0 ^ _ ^ _ ^ _ ^ _ ^
process 1 0 _ _ _ -> AC 1 ^ _ ^ _ ^ _ ^ _ ^
process 0 30 _ _ _ -> parse_numbers 0 ^ 29 > 0 ^ _ ^ _ ^
process 1 30 _ _ _ -> parse_numbers 1 ^ 29 > 0 ^ _ ^ _ ^
process 0 29 _ _ _ -> parse_numbers 0 ^ 28 > 0 ^ _ ^ _ ^
process 1 29 _ _ _ -> parse_numbers 1 ^ 28 > 0 ^ _ ^ _ ^
process 0 28 _ _ _ -> parse_numbers 0 ^ 27 > 0 ^ _ ^ _ ^
process 1 28 _ _ _ -> parse_numbers 1 ^ 27 > 0 ^ _ ^ _ ^
process 0 27 _ _ _ -> parse_numbers 0 ^ 26 > 0 ^ _ ^ _ ^
process 1 27 _ _ _ -> parse_numbers 1 ^ 26 > 0 ^ _ ^ _ ^
process 0 26 _ _ _ -> parse_numbers 0 ^ 25 > 0 ^ _ ^ _ ^
process 1 26 _ _ _ -> parse_numbers 1 ^ 25 > 0 ^ _ ^ _ ^
process 0 25 _ _ _ -> parse_numbers 0 ^ 24 > 0 ^ _ ^ _ ^
process 1 25 _ _ _ -> parse_numbers 1 ^ 24 > 0 ^ _ ^ _ ^
process 0 24 _ _ _ -> parse_numbers 0 ^ 23 > 0 ^ _ ^ _ ^
process 1 24 _ _ _ -> parse_numbers 1 ^ 23 > 0 ^ _ ^ _ ^
process 0 23 _ _ _ -> parse_numbers 0 ^ 22 > 0 ^ _ ^ _ ^
process 1 23 _ _ _ -> parse_numbers 1 ^ 22 > 0 ^ _ ^ _ ^
process 0 22 _ _ _ -> parse_numbers 0 ^ 21 > 0 ^ _ ^ _ ^
process 1 22 _ _ _ -> parse_numbers 1 ^ 21 > 0 ^ _ ^ _ ^
process 0 21 _ _ _ -> parse_numbers 0 ^ 20 > 0 ^ _ ^ _ ^
process 1 21 _ _ _ -> parse_numbers 1 ^ 20 > 0 ^ _ ^ _ ^
process 0 20 _ _ _ -> parse_numbers 0 ^ 19 > 0 ^ _ ^ _ ^
process 1 20 _ _ _ -> parse_numbers 1 ^ 19 > 0 ^ _ ^ _ ^
process 0 19 _ _ _ -> parse_numbers 0 ^ 18 > 0 ^ _ ^ _ ^
process 1 19 _ _ _ -> parse_numbers 1 ^ 18 > 0 ^ _ ^ _ ^
process 0 18 _ _ _ -> parse_numbers 0 ^ 17 > 0 ^ _ ^ _ ^
process 1 18 _ _ _ -> parse_numbers 1 ^ 17 > 0 ^ _ ^ _ ^
process 0 17 _ _ _ -> parse_numbers 0 ^ 16 > 0 ^ _ ^ _ ^
process 1 17 _ _ _ -> parse_numbers 1 ^ 16 > 0 ^ _ ^ _ ^
process 0 16 _ _ _ -> parse_numbers 0 ^ 15 > 0 ^ _ ^ _ ^
process 1 16 _ _ _ -> parse_numbers 1 ^ 15 > 0 ^ _ ^ _ ^
process 0 15 _ _ _ -> parse_numbers 0 ^ 14 > 0 ^ _ ^ _ ^
process 1 15 _ _ _ -> parse_numbers 1 ^ 14 > 0 ^ _ ^ _ ^
process 0 14 _ _ _ -> parse_numbers 0 ^ 13 > 0 ^ _ ^ _ ^
process 1 14 _ _ _ -> parse_numbers 1 ^ 13 > 0 ^ _ ^ _ ^
process 0 13 _ _ _ -> parse_numbers 0 ^ 12 > 0 ^ _ ^ _ ^
process 1 13 _ _ _ -> parse_numbers 1 ^ 12 > 0 ^ _ ^ _ ^
process 0 12 _ _ _ -> parse_numbers 0 ^ 11 > 0 ^ _ ^ _ ^
process 1 12 _ _ _ -> parse_numbers 1 ^ 11 > 0 ^ _ ^ _ ^
process 0 11 _ _ _ -> parse_numbers 0 ^ 10 > 0 ^ _ ^ _ ^
process 1 11 _ _ _ -> parse_numbers 1 ^ 10 > 0 ^ _ ^ _ ^
process 0 10 _ _ _ -> parse_numbers 0 ^ 9 > 0 ^ _ ^ _ ^
process 1 10 _ _ _ -> parse_numbers 1 ^ 9 > 0 ^ _ ^ _ ^
process 0 9 _ _ _ -> parse_numbers 0 ^ 8 > 0 ^ _ ^ _ ^
process 1 9 _ _ _ -> parse_numbers 1 ^ 8 > 0 ^ _ ^ _ ^
process 0 8 _ _ _ -> parse_numbers 0 ^ 7 > 0 ^ _ ^ _ ^
process 1 8 _ _ _ -> parse_numbers 1 ^ 7 > 0 ^ _ ^ _ ^
process 0 7 _ _ _ -> parse_numbers 0 ^ 6 > 0 ^ _ ^ _ ^
process 1 7 _ _ _ -> parse_numbers 1 ^ 6 > 0 ^ _ ^ _ ^
process 0 6 _ _ _ -> parse_numbers 0 ^ 5 > 0 ^ _ ^ _ ^
process 1 6 _ _ _ -> parse_numbers 1 ^ 5 > 0 ^ _ ^ _ ^
process 0 5 _ _ _ -> parse_numbers 0 ^ 4 > 0 ^ _ ^ _ ^
process 1 5 _ _ _ -> parse_numbers 1 ^ 4 > 0 ^ _ ^ _ ^
process 0 4 _ _ _ -> parse_numbers 0 ^ 3 > 0 ^ _ ^ _ ^
process 1 4 _ _ _ -> parse_numbers 1 ^ 3 > 0 ^ _ ^ _ ^
process 0 3 _ _ _ -> parse_numbers 0 ^ 2 > 0 ^ _ ^ _ ^
process 1 3 _ _ _ -> parse_numbers 1 ^ 2 > 0 ^ _ ^ _ ^
process 0 2 _ _ _ -> parse_numbers 0 ^ 1 > 0 ^ _ ^ _ ^
process 1 2 _ _ _ -> parse_numbers 1 ^ 1 > 0 ^ _ ^ _ ^
process 0 1 _ _ _ -> parse_numbers 0 ^ 0 > 0 ^ _ ^ _ ^
process 1 1 _ _ _ -> parse_numbers 1 ^ 0 > 0 ^ _ ^ _ ^
parse_numbers 0 _ -15 _ _ -> parse_numbers _ > _ ^ -14 ^ 0 > _ ^
parse_numbers 1 _ -15 _ _ -> parse_numbers _ > _ ^ -14 ^ 1 > _ ^
parse_numbers _ _ -15 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -15 _ _ -> second_parse _ > _ ^ -15 ^ _ ^ _ ^
second_parse 0 _ -15 _ _ -> second_parse _ > _ ^ -16 ^ _ ^ 0 >
second_parse 1 _ -15 _ _ -> second_parse _ > _ ^ -16 ^ _ ^ 1 >
second_parse | _ -15 _ _ -> compare | < _ ^ -15 ^ _ ^ _ ^
second_parse _ _ -15 _ _ -> compare _ < _ ^ -15 ^ _ ^ _ ^
parse_numbers 0 _ -14 _ _ -> parse_numbers _ > _ ^ -13 ^ 0 > _ ^
parse_numbers 1 _ -14 _ _ -> parse_numbers _ > _ ^ -13 ^ 1 > _ ^
parse_numbers _ _ -14 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -14 _ _ -> second_parse _ > _ ^ -14 ^ _ ^ _ ^
second_parse 0 _ -14 _ _ -> second_parse _ > _ ^ -15 ^ _ ^ 0 >
second_parse 1 _ -14 _ _ -> second_parse _ > _ ^ -15 ^ _ ^ 1 >
second_parse | _ -14 _ _ -> compare | < _ ^ -14 ^ _ ^ _ ^
second_parse _ _ -14 _ _ -> compare _ < _ ^ -14 ^ _ ^ _ ^
parse_numbers 0 _ -13 _ _ -> parse_numbers _ > _ ^ -12 ^ 0 > _ ^
parse_numbers 1 _ -13 _ _ -> parse_numbers _ > _ ^ -12 ^ 1 > _ ^
parse_numbers _ _ -13 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -13 _ _ -> second_parse _ > _ ^ -13 ^ _ ^ _ ^
second_parse 0 _ -13 _ _ -> second_parse _ > _ ^ -14 ^ _ ^ 0 >
second_parse 1 _ -13 _ _ -> second_parse _ > _ ^ -14 ^ _ ^ 1 >
second_parse | _ -13 _ _ -> compare | < _ ^ -13 ^ _ ^ _ ^
second_parse _ _ -13 _ _ -> compare _ < _ ^ -13 ^ _ ^ _ ^
parse_numbers 0 _ -12 _ _ -> parse_numbers _ > _ ^ -11 ^ 0 > _ ^
parse_numbers 1 _ -12 _ _ -> parse_numbers _ > _ ^ -11 ^ 1 > _ ^
parse_numbers _ _ -12 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -12 _ _ -> second_parse _ > _ ^ -12 ^ _ ^ _ ^
second_parse 0 _ -12 _ _ -> second_parse _ > _ ^ -13 ^ _ ^ 0 >
second_parse 1 _ -12 _ _ -> second_parse _ > _ ^ -13 ^ _ ^ 1 >
second_parse | _ -12 _ _ -> compare | < _ ^ -12 ^ _ ^ _ ^
second_parse _ _ -12 _ _ -> compare _ < _ ^ -12 ^ _ ^ _ ^
parse_numbers 0 _ -11 _ _ -> parse_numbers _ > _ ^ -10 ^ 0 > _ ^
parse_numbers 1 _ -11 _ _ -> parse_numbers _ > _ ^ -10 ^ 1 > _ ^
parse_numbers _ _ -11 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -11 _ _ -> second_parse _ > _ ^ -11 ^ _ ^ _ ^
second_parse 0 _ -11 _ _ -> second_parse _ > _ ^ -12 ^ _ ^ 0 >
second_parse 1 _ -11 _ _ -> second_parse _ > _ ^ -12 ^ _ ^ 1 >
second_parse | _ -11 _ _ -> compare | < _ ^ -11 ^ _ ^ _ ^
second_parse _ _ -11 _ _ -> compare _ < _ ^ -11 ^ _ ^ _ ^
parse_numbers 0 _ -10 _ _ -> parse_numbers _ > _ ^ -9 ^ 0 > _ ^
parse_numbers 1 _ -10 _ _ -> parse_numbers _ > _ ^ -9 ^ 1 > _ ^
parse_numbers _ _ -10 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -10 _ _ -> second_parse _ > _ ^ -10 ^ _ ^ _ ^
second_parse 0 _ -10 _ _ -> second_parse _ > _ ^ -11 ^ _ ^ 0 >
second_parse 1 _ -10 _ _ -> second_parse _ > _ ^ -11 ^ _ ^ 1 >
second_parse | _ -10 _ _ -> compare | < _ ^ -10 ^ _ ^ _ ^
second_parse _ _ -10 _ _ -> compare _ < _ ^ -10 ^ _ ^ _ ^
parse_numbers 0 _ -9 _ _ -> parse_numbers _ > _ ^ -8 ^ 0 > _ ^
parse_numbers 1 _ -9 _ _ -> parse_numbers _ > _ ^ -8 ^ 1 > _ ^
parse_numbers _ _ -9 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -9 _ _ -> second_parse _ > _ ^ -9 ^ _ ^ _ ^
second_parse 0 _ -9 _ _ -> second_parse _ > _ ^ -10 ^ _ ^ 0 >
second_parse 1 _ -9 _ _ -> second_parse _ > _ ^ -10 ^ _ ^ 1 >
second_parse | _ -9 _ _ -> compare | < _ ^ -9 ^ _ ^ _ ^
second_parse _ _ -9 _ _ -> compare _ < _ ^ -9 ^ _ ^ _ ^
parse_numbers 0 _ -8 _ _ -> parse_numbers _ > _ ^ -7 ^ 0 > _ ^
parse_numbers 1 _ -8 _ _ -> parse_numbers _ > _ ^ -7 ^ 1 > _ ^
parse_numbers _ _ -8 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -8 _ _ -> second_parse _ > _ ^ -8 ^ _ ^ _ ^
second_parse 0 _ -8 _ _ -> second_parse _ > _ ^ -9 ^ _ ^ 0 >
second_parse 1 _ -8 _ _ -> second_parse _ > _ ^ -9 ^ _ ^ 1 >
second_parse | _ -8 _ _ -> compare | < _ ^ -8 ^ _ ^ _ ^
second_parse _ _ -8 _ _ -> compare _ < _ ^ -8 ^ _ ^ _ ^
parse_numbers 0 _ -7 _ _ -> parse_numbers _ > _ ^ -6 ^ 0 > _ ^
parse_numbers 1 _ -7 _ _ -> parse_numbers _ > _ ^ -6 ^ 1 > _ ^
parse_numbers _ _ -7 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -7 _ _ -> second_parse _ > _ ^ -7 ^ _ ^ _ ^
second_parse 0 _ -7 _ _ -> second_parse _ > _ ^ -8 ^ _ ^ 0 >
second_parse 1 _ -7 _ _ -> second_parse _ > _ ^ -8 ^ _ ^ 1 >
second_parse | _ -7 _ _ -> compare | < _ ^ -7 ^ _ ^ _ ^
second_parse _ _ -7 _ _ -> compare _ < _ ^ -7 ^ _ ^ _ ^
parse_numbers 0 _ -6 _ _ -> parse_numbers _ > _ ^ -5 ^ 0 > _ ^
parse_numbers 1 _ -6 _ _ -> parse_numbers _ > _ ^ -5 ^ 1 > _ ^
parse_numbers _ _ -6 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -6 _ _ -> second_parse _ > _ ^ -6 ^ _ ^ _ ^
second_parse 0 _ -6 _ _ -> second_parse _ > _ ^ -7 ^ _ ^ 0 >
second_parse 1 _ -6 _ _ -> second_parse _ > _ ^ -7 ^ _ ^ 1 >
second_parse | _ -6 _ _ -> compare | < _ ^ -6 ^ _ ^ _ ^
second_parse _ _ -6 _ _ -> compare _ < _ ^ -6 ^ _ ^ _ ^
parse_numbers 0 _ -5 _ _ -> parse_numbers _ > _ ^ -4 ^ 0 > _ ^
parse_numbers 1 _ -5 _ _ -> parse_numbers _ > _ ^ -4 ^ 1 > _ ^
parse_numbers _ _ -5 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -5 _ _ -> second_parse _ > _ ^ -5 ^ _ ^ _ ^
second_parse 0 _ -5 _ _ -> second_parse _ > _ ^ -6 ^ _ ^ 0 >
second_parse 1 _ -5 _ _ -> second_parse _ > _ ^ -6 ^ _ ^ 1 >
second_parse | _ -5 _ _ -> compare | < _ ^ -5 ^ _ ^ _ ^
second_parse _ _ -5 _ _ -> compare _ < _ ^ -5 ^ _ ^ _ ^
parse_numbers 0 _ -4 _ _ -> parse_numbers _ > _ ^ -3 ^ 0 > _ ^
parse_numbers 1 _ -4 _ _ -> parse_numbers _ > _ ^ -3 ^ 1 > _ ^
parse_numbers _ _ -4 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -4 _ _ -> second_parse _ > _ ^ -4 ^ _ ^ _ ^
second_parse 0 _ -4 _ _ -> second_parse _ > _ ^ -5 ^ _ ^ 0 >
second_parse 1 _ -4 _ _ -> second_parse _ > _ ^ -5 ^ _ ^ 1 >
second_parse | _ -4 _ _ -> compare | < _ ^ -4 ^ _ ^ _ ^
second_parse _ _ -4 _ _ -> compare _ < _ ^ -4 ^ _ ^ _ ^
parse_numbers 0 _ -3 _ _ -> parse_numbers _ > _ ^ -2 ^ 0 > _ ^
parse_numbers 1 _ -3 _ _ -> parse_numbers _ > _ ^ -2 ^ 1 > _ ^
parse_numbers _ _ -3 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -3 _ _ -> second_parse _ > _ ^ -3 ^ _ ^ _ ^
second_parse 0 _ -3 _ _ -> second_parse _ > _ ^ -4 ^ _ ^ 0 >
second_parse 1 _ -3 _ _ -> second_parse _ > _ ^ -4 ^ _ ^ 1 >
second_parse | _ -3 _ _ -> compare | < _ ^ -3 ^ _ ^ _ ^
second_parse _ _ -3 _ _ -> compare _ < _ ^ -3 ^ _ ^ _ ^
parse_numbers 0 _ -2 _ _ -> parse_numbers _ > _ ^ -1 ^ 0 > _ ^
parse_numbers 1 _ -2 _ _ -> parse_numbers _ > _ ^ -1 ^ 1 > _ ^
parse_numbers _ _ -2 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -2 _ _ -> second_parse _ > _ ^ -2 ^ _ ^ _ ^
second_parse 0 _ -2 _ _ -> second_parse _ > _ ^ -3 ^ _ ^ 0 >
second_parse 1 _ -2 _ _ -> second_parse _ > _ ^ -3 ^ _ ^ 1 >
second_parse | _ -2 _ _ -> compare | < _ ^ -2 ^ _ ^ _ ^
second_parse _ _ -2 _ _ -> compare _ < _ ^ -2 ^ _ ^ _ ^
parse_numbers 0 _ -1 _ _ -> parse_numbers _ > _ ^ 0 ^ 0 > _ ^
parse_numbers 1 _ -1 _ _ -> parse_numbers _ > _ ^ 0 ^ 1 > _ ^
parse_numbers _ _ -1 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ -1 _ _ -> second_parse _ > _ ^ -1 ^ _ ^ _ ^
second_parse 0 _ -1 _ _ -> second_parse _ > _ ^ -2 ^ _ ^ 0 >
second_parse 1 _ -1 _ _ -> second_parse _ > _ ^ -2 ^ _ ^ 1 >
second_parse | _ -1 _ _ -> compare | < _ ^ -1 ^ _ ^ _ ^
second_parse _ _ -1 _ _ -> compare _ < _ ^ -1 ^ _ ^ _ ^
parse_numbers 0 _ 0 _ _ -> parse_numbers _ > _ ^ 1 ^ 0 > _ ^
parse_numbers 1 _ 0 _ _ -> parse_numbers _ > _ ^ 1 ^ 1 > _ ^
parse_numbers _ _ 0 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 0 _ _ -> second_parse _ > _ ^ 0 ^ _ ^ _ ^
second_parse 0 _ 0 _ _ -> second_parse _ > _ ^ -1 ^ _ ^ 0 >
second_parse 1 _ 0 _ _ -> second_parse _ > _ ^ -1 ^ _ ^ 1 >
second_parse | _ 0 _ _ -> compare | < _ ^ 0 ^ _ ^ _ ^
second_parse _ _ 0 _ _ -> compare _ < _ ^ 0 ^ _ ^ _ ^
parse_numbers 0 _ 1 _ _ -> parse_numbers _ > _ ^ 2 ^ 0 > _ ^
parse_numbers 1 _ 1 _ _ -> parse_numbers _ > _ ^ 2 ^ 1 > _ ^
parse_numbers _ _ 1 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 1 _ _ -> second_parse _ > _ ^ 1 ^ _ ^ _ ^
second_parse 0 _ 1 _ _ -> second_parse _ > _ ^ 0 ^ _ ^ 0 >
second_parse 1 _ 1 _ _ -> second_parse _ > _ ^ 0 ^ _ ^ 1 >
second_parse | _ 1 _ _ -> compare | < _ ^ 1 ^ _ ^ _ ^
second_parse _ _ 1 _ _ -> compare _ < _ ^ 1 ^ _ ^ _ ^
parse_numbers 0 _ 2 _ _ -> parse_numbers _ > _ ^ 3 ^ 0 > _ ^
parse_numbers 1 _ 2 _ _ -> parse_numbers _ > _ ^ 3 ^ 1 > _ ^
parse_numbers _ _ 2 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 2 _ _ -> second_parse _ > _ ^ 2 ^ _ ^ _ ^
second_parse 0 _ 2 _ _ -> second_parse _ > _ ^ 1 ^ _ ^ 0 >
second_parse 1 _ 2 _ _ -> second_parse _ > _ ^ 1 ^ _ ^ 1 >
second_parse | _ 2 _ _ -> compare | < _ ^ 2 ^ _ ^ _ ^
second_parse _ _ 2 _ _ -> compare _ < _ ^ 2 ^ _ ^ _ ^
parse_numbers 0 _ 3 _ _ -> parse_numbers _ > _ ^ 4 ^ 0 > _ ^
parse_numbers 1 _ 3 _ _ -> parse_numbers _ > _ ^ 4 ^ 1 > _ ^
parse_numbers _ _ 3 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 3 _ _ -> second_parse _ > _ ^ 3 ^ _ ^ _ ^
second_parse 0 _ 3 _ _ -> second_parse _ > _ ^ 2 ^ _ ^ 0 >
second_parse 1 _ 3 _ _ -> second_parse _ > _ ^ 2 ^ _ ^ 1 >
second_parse | _ 3 _ _ -> compare | < _ ^ 3 ^ _ ^ _ ^
second_parse _ _ 3 _ _ -> compare _ < _ ^ 3 ^ _ ^ _ ^
parse_numbers 0 _ 4 _ _ -> parse_numbers _ > _ ^ 5 ^ 0 > _ ^
parse_numbers 1 _ 4 _ _ -> parse_numbers _ > _ ^ 5 ^ 1 > _ ^
parse_numbers _ _ 4 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 4 _ _ -> second_parse _ > _ ^ 4 ^ _ ^ _ ^
second_parse 0 _ 4 _ _ -> second_parse _ > _ ^ 3 ^ _ ^ 0 >
second_parse 1 _ 4 _ _ -> second_parse _ > _ ^ 3 ^ _ ^ 1 >
second_parse | _ 4 _ _ -> compare | < _ ^ 4 ^ _ ^ _ ^
second_parse _ _ 4 _ _ -> compare _ < _ ^ 4 ^ _ ^ _ ^
parse_numbers 0 _ 5 _ _ -> parse_numbers _ > _ ^ 6 ^ 0 > _ ^
parse_numbers 1 _ 5 _ _ -> parse_numbers _ > _ ^ 6 ^ 1 > _ ^
parse_numbers _ _ 5 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 5 _ _ -> second_parse _ > _ ^ 5 ^ _ ^ _ ^
second_parse 0 _ 5 _ _ -> second_parse _ > _ ^ 4 ^ _ ^ 0 >
second_parse 1 _ 5 _ _ -> second_parse _ > _ ^ 4 ^ _ ^ 1 >
second_parse | _ 5 _ _ -> compare | < _ ^ 5 ^ _ ^ _ ^
second_parse _ _ 5 _ _ -> compare _ < _ ^ 5 ^ _ ^ _ ^
parse_numbers 0 _ 6 _ _ -> parse_numbers _ > _ ^ 7 ^ 0 > _ ^
parse_numbers 1 _ 6 _ _ -> parse_numbers _ > _ ^ 7 ^ 1 > _ ^
parse_numbers _ _ 6 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 6 _ _ -> second_parse _ > _ ^ 6 ^ _ ^ _ ^
second_parse 0 _ 6 _ _ -> second_parse _ > _ ^ 5 ^ _ ^ 0 >
second_parse 1 _ 6 _ _ -> second_parse _ > _ ^ 5 ^ _ ^ 1 >
second_parse | _ 6 _ _ -> compare | < _ ^ 6 ^ _ ^ _ ^
second_parse _ _ 6 _ _ -> compare _ < _ ^ 6 ^ _ ^ _ ^
parse_numbers 0 _ 7 _ _ -> parse_numbers _ > _ ^ 8 ^ 0 > _ ^
parse_numbers 1 _ 7 _ _ -> parse_numbers _ > _ ^ 8 ^ 1 > _ ^
parse_numbers _ _ 7 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 7 _ _ -> second_parse _ > _ ^ 7 ^ _ ^ _ ^
second_parse 0 _ 7 _ _ -> second_parse _ > _ ^ 6 ^ _ ^ 0 >
second_parse 1 _ 7 _ _ -> second_parse _ > _ ^ 6 ^ _ ^ 1 >
second_parse | _ 7 _ _ -> compare | < _ ^ 7 ^ _ ^ _ ^
second_parse _ _ 7 _ _ -> compare _ < _ ^ 7 ^ _ ^ _ ^
parse_numbers 0 _ 8 _ _ -> parse_numbers _ > _ ^ 9 ^ 0 > _ ^
parse_numbers 1 _ 8 _ _ -> parse_numbers _ > _ ^ 9 ^ 1 > _ ^
parse_numbers _ _ 8 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 8 _ _ -> second_parse _ > _ ^ 8 ^ _ ^ _ ^
second_parse 0 _ 8 _ _ -> second_parse _ > _ ^ 7 ^ _ ^ 0 >
second_parse 1 _ 8 _ _ -> second_parse _ > _ ^ 7 ^ _ ^ 1 >
second_parse | _ 8 _ _ -> compare | < _ ^ 8 ^ _ ^ _ ^
second_parse _ _ 8 _ _ -> compare _ < _ ^ 8 ^ _ ^ _ ^
parse_numbers 0 _ 9 _ _ -> parse_numbers _ > _ ^ 10 ^ 0 > _ ^
parse_numbers 1 _ 9 _ _ -> parse_numbers _ > _ ^ 10 ^ 1 > _ ^
parse_numbers _ _ 9 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 9 _ _ -> second_parse _ > _ ^ 9 ^ _ ^ _ ^
second_parse 0 _ 9 _ _ -> second_parse _ > _ ^ 8 ^ _ ^ 0 >
second_parse 1 _ 9 _ _ -> second_parse _ > _ ^ 8 ^ _ ^ 1 >
second_parse | _ 9 _ _ -> compare | < _ ^ 9 ^ _ ^ _ ^
second_parse _ _ 9 _ _ -> compare _ < _ ^ 9 ^ _ ^ _ ^
parse_numbers 0 _ 10 _ _ -> parse_numbers _ > _ ^ 11 ^ 0 > _ ^
parse_numbers 1 _ 10 _ _ -> parse_numbers _ > _ ^ 11 ^ 1 > _ ^
parse_numbers _ _ 10 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 10 _ _ -> second_parse _ > _ ^ 10 ^ _ ^ _ ^
second_parse 0 _ 10 _ _ -> second_parse _ > _ ^ 9 ^ _ ^ 0 >
second_parse 1 _ 10 _ _ -> second_parse _ > _ ^ 9 ^ _ ^ 1 >
second_parse | _ 10 _ _ -> compare | < _ ^ 10 ^ _ ^ _ ^
second_parse _ _ 10 _ _ -> compare _ < _ ^ 10 ^ _ ^ _ ^
parse_numbers 0 _ 11 _ _ -> parse_numbers _ > _ ^ 12 ^ 0 > _ ^
parse_numbers 1 _ 11 _ _ -> parse_numbers _ > _ ^ 12 ^ 1 > _ ^
parse_numbers _ _ 11 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 11 _ _ -> second_parse _ > _ ^ 11 ^ _ ^ _ ^
second_parse 0 _ 11 _ _ -> second_parse _ > _ ^ 10 ^ _ ^ 0 >
second_parse 1 _ 11 _ _ -> second_parse _ > _ ^ 10 ^ _ ^ 1 >
second_parse | _ 11 _ _ -> compare | < _ ^ 11 ^ _ ^ _ ^
second_parse _ _ 11 _ _ -> compare _ < _ ^ 11 ^ _ ^ _ ^
parse_numbers 0 _ 12 _ _ -> parse_numbers _ > _ ^ 13 ^ 0 > _ ^
parse_numbers 1 _ 12 _ _ -> parse_numbers _ > _ ^ 13 ^ 1 > _ ^
parse_numbers _ _ 12 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 12 _ _ -> second_parse _ > _ ^ 12 ^ _ ^ _ ^
second_parse 0 _ 12 _ _ -> second_parse _ > _ ^ 11 ^ _ ^ 0 >
second_parse 1 _ 12 _ _ -> second_parse _ > _ ^ 11 ^ _ ^ 1 >
second_parse | _ 12 _ _ -> compare | < _ ^ 12 ^ _ ^ _ ^
second_parse _ _ 12 _ _ -> compare _ < _ ^ 12 ^ _ ^ _ ^
parse_numbers 0 _ 13 _ _ -> parse_numbers _ > _ ^ 14 ^ 0 > _ ^
parse_numbers 1 _ 13 _ _ -> parse_numbers _ > _ ^ 14 ^ 1 > _ ^
parse_numbers _ _ 13 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 13 _ _ -> second_parse _ > _ ^ 13 ^ _ ^ _ ^
second_parse 0 _ 13 _ _ -> second_parse _ > _ ^ 12 ^ _ ^ 0 >
second_parse 1 _ 13 _ _ -> second_parse _ > _ ^ 12 ^ _ ^ 1 >
second_parse | _ 13 _ _ -> compare | < _ ^ 13 ^ _ ^ _ ^
second_parse _ _ 13 _ _ -> compare _ < _ ^ 13 ^ _ ^ _ ^
parse_numbers 0 _ 14 _ _ -> parse_numbers _ > _ ^ 15 ^ 0 > _ ^
parse_numbers 1 _ 14 _ _ -> parse_numbers _ > _ ^ 15 ^ 1 > _ ^
parse_numbers _ _ 14 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 14 _ _ -> second_parse _ > _ ^ 14 ^ _ ^ _ ^
second_parse 0 _ 14 _ _ -> second_parse _ > _ ^ 13 ^ _ ^ 0 >
second_parse 1 _ 14 _ _ -> second_parse _ > _ ^ 13 ^ _ ^ 1 >
second_parse | _ 14 _ _ -> compare | < _ ^ 14 ^ _ ^ _ ^
second_parse _ _ 14 _ _ -> compare _ < _ ^ 14 ^ _ ^ _ ^
parse_numbers 0 _ 15 _ _ -> parse_numbers _ > _ ^ 16 ^ 0 > _ ^
parse_numbers 1 _ 15 _ _ -> parse_numbers _ > _ ^ 16 ^ 1 > _ ^
parse_numbers _ _ 15 _ _ -> finally _ < _ ^ _ ^ _ < _ ^
parse_numbers | _ 15 _ _ -> second_parse _ > _ ^ 15 ^ _ ^ _ ^
second_parse 0 _ 15 _ _ -> second_parse _ > _ ^ 14 ^ _ ^ 0 >
second_parse 1 _ 15 _ _ -> second_parse _ > _ ^ 14 ^ _ ^ 1 >
second_parse | _ 15 _ _ -> compare | < _ ^ 15 ^ _ ^ _ ^
second_parse _ _ 15 _ _ -> compare _ < _ ^ 15 ^ _ ^ _ ^
finally _ _ _ 0 _ -> finally 0 < _ ^ _ ^ _ < _ ^
finally _ _ _ 1 _ -> finally 1 < _ ^ _ ^ _ < _ ^
finally | _ _ _ _ -> go_left | ^ _ ^ _ ^ _ ^ _ ^
finally _ _ _ _ _ -> go_left _ ^ _ ^ _ ^ _ ^ _ ^
go_left 0 _ _ _ _ -> go_left 0 < _ ^ _ ^ _ ^ _ ^
go_left 1 _ _ _ _ -> go_left 1 < _ ^ _ ^ _ ^ _ ^
go_left | _ _ _ _ -> go_left | < _ ^ _ ^ _ ^ _ ^
go_left _ _ _ _ _ -> process _ > _ < _ ^ _ ^ _ ^
compare _ _ -15 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -14 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -13 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -12 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -11 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -10 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -9 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -8 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -7 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -6 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -5 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -4 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -3 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -2 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ -1 _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 1 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 2 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 3 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 4 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 5 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 6 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 7 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 8 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 9 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 10 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 11 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 12 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 13 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 14 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 15 _ _ -> return_swap _ ^ _ ^ _ ^ _ ^ _ ^
compare _ _ 0 _ _ -> compare_it_goleft _ ^ _ ^ _ ^ _ < _ <
compare_it_goleft _ _ _ 0 0 -> compare_it_goleft _ ^ _ ^ _ ^ 0 < 0 <
compare_it_goleft _ _ _ 0 1 -> compare_it_goleft _ ^ _ ^ _ ^ 0 < 1 <
compare_it_goleft _ _ _ 1 0 -> compare_it_goleft _ ^ _ ^ _ ^ 1 < 0 <
compare_it_goleft _ _ _ 1 1 -> compare_it_goleft _ ^ _ ^ _ ^ 1 < 1 <
compare_it_goleft _ _ _ _ _ -> compare_it _ ^ _ ^ _ ^ _ > _ >
compare_it _ _ _ 0 0 -> compare_it _ ^ _ ^ _ ^ 0 > 0 >
compare_it _ _ _ 0 1 -> return_not_swap _ ^ _ ^ _ ^ 0 > 1 >
compare_it _ _ _ 1 0 -> return_swap _ ^ _ ^ _ ^ 1 > 0 >
compare_it _ _ _ 1 1 -> compare_it _ ^ _ ^ _ ^ 1 > 1 >
compare_it _ _ _ _ _ -> return_not_swap _ ^ _ ^ _ ^ _ ^ _ ^
return_not_swap _ _ _ 0 0 -> return_not_swap _ ^ _ ^ _ ^ 0 > 0 >
return_not_swap _ _ _ 0 1 -> return_not_swap _ ^ _ ^ _ ^ 0 > 1 >
return_not_swap _ _ _ 0 _ -> return_not_swap _ ^ _ ^ _ ^ 0 > _ ^
return_not_swap _ _ _ 1 0 -> return_not_swap _ ^ _ ^ _ ^ 1 > 0 >
return_not_swap _ _ _ 1 1 -> return_not_swap _ ^ _ ^ _ ^ 1 > 1 >
return_not_swap _ _ _ 1 _ -> return_not_swap _ ^ _ ^ _ ^ 1 > _ ^
return_not_swap _ _ _ _ 0 -> return_not_swap _ ^ _ ^ _ ^ _ ^ 0 >
return_not_swap _ _ _ _ 1 -> return_not_swap _ ^ _ ^ _ ^ _ ^ 1 >
return_not_swap _ _ _ _ _ -> output_2 _ ^ _ ^ _ ^ _ ^ _ <
output_0 _ _ _ 0 _ -> output_0 0 < _ ^ _ ^ _ < _ ^
output_0 _ _ _ 1 _ -> output_0 1 < _ ^ _ ^ _ < _ ^
output_2 _ _ _ _ 0 -> output_2 0 < _ ^ _ ^ _ ^ _ <
output_2 _ _ _ _ 1 -> output_2 1 < _ ^ _ ^ _ ^ _ <
output_2 | _ _ _ _ -> output_0 | < _ ^ _ ^ _ < _ ^
output_2 _ _ _ _ _ -> output_0 | < _ ^ _ ^ _ < _ ^
output_0 | _ _ _ _ -> go_right | > _ ^ _ ^ _ ^ _ ^
output_0 _ _ _ _ _ -> go_right _ > _ ^ _ ^ _ ^ _ ^
return_swap _ _ _ 0 0 -> return_swap _ ^ _ ^ _ ^ 0 > 0 >
return_swap _ _ _ 1 0 -> return_swap _ ^ _ ^ _ ^ 1 > 0 >
return_swap _ _ _ _ 0 -> return_swap _ ^ _ ^ _ ^ _ ^ 0 >
return_swap _ _ _ 0 1 -> return_swap _ ^ _ ^ _ ^ 0 > 1 >
return_swap _ _ _ 1 1 -> return_swap _ ^ _ ^ _ ^ 1 > 1 >
return_swap _ _ _ _ 1 -> return_swap _ ^ _ ^ _ ^ _ ^ 1 >
return_swap _ _ _ 0 _ -> return_swap _ ^ _ ^ _ ^ 0 > _ ^
return_swap _ _ _ 1 _ -> return_swap _ ^ _ ^ _ ^ 1 > _ ^
return_swap _ _ _ _ _ -> output_3 _ ^ _ ^ _ ^ _ < _ ^
output_1 _ _ _ _ 0 -> output_1 0 < _ ^ _ ^ _ ^ _ <
output_1 _ _ _ _ 1 -> output_1 1 < _ ^ _ ^ _ ^ _ <
output_3 _ _ _ 0 _ -> output_3 0 < _ ^ _ ^ _ < _ ^
output_3 _ _ _ 1 _ -> output_3 1 < _ ^ _ ^ _ < _ ^
output_3 | _ _ _ _ -> output_1 | < _ ^ _ ^ _ ^ _ <
output_3 _ _ _ _ _ -> output_1 | < _ ^ _ ^ _ ^ _ <
output_1 | _ _ _ _ -> go_right | > _ ^ _ ^ _ ^ _ ^
output_1 _ _ _ _ _ -> go_right _ > _ ^ _ ^ _ ^ _ ^
go_right 0 _ _ _ _ -> go_right 0 > _ ^ _ ^ _ ^ _ ^
go_right 1 _ _ _ _ -> go_right 1 > _ ^ _ ^ _ ^ _ ^
go_right | _ _ _ _ -> parse_numbers | > _ ^ 0 ^ _ ^ _ ^''')
 
if __name__ == '__main__':
    main()